### ISSUE TITLE
Move tool configuration from .pre-commit-config.yaml to pyproject.toml

### ISSUE THREAD

**Issue by plule-ansys** [pyansys/ansys-templates#50]
When configuring an IDE, it's common to use "format on save" feature that triggers linter each time you save. Unfortunately, in my case, black would format to its default of 88 character per lines, that were clashing with the pre-commit's 100 characters.

If this configuration is moved into `pyproject.toml`, then both pre-commit and the IDE (or just black called independently) are able to interpret it, solving the issue.

FYI, I've applied this fix in https://github.com/pyansys/pypim/pull/6 This fix omits pydocstyle as I'm not very confortable with this tools usage.

**Comment by greschd** [comment]
> From my point of view, all code style configuration must be collected under a common file, the pre-commit-config.yaml one. This introduces safety: all conf is declared in a single file.

I'd have to disagree quite strongly with that. Overall, `.pre-commit-config.yaml` is a pretty "niche" config file, whereas `pyproject.toml` is the standard many tools gravitate towards. So I would reverse this: put all configuration into `pyproject.toml`, and only the actual invocation of the tool into `.pre-commit-config.yaml`.

This works also for other tools such as mypy, isort, pylint, ... and many other tools. FMPOV, it's an anti-pattern to pass command-line arguments to the formatter and other tools (in `.pre-commit-config.yaml`) instead of using a config file (mostly `pyproject.toml`, there may be few exceptions) to configure them.

**Comment by jorgepiloto** [comment]
Before implementing this, I will address #48 first, so everything is unified under a common `pyproject.toml`.

**Comment by jorgepiloto** [comment]
This was partially addressed in #53. Labeling it now as "blocked" till https://github.com/PyCQA/flake8/issues/234 and https://github.com/codespell-project/codespell/issues/2055 are implemented.

**Comment by plule-ansys** [comment]
@jorgepiloto As far as I'm concerned, I think the issue can be closed. The critical path is for tools that modify your code. The tools that just run checks are less likely to be used externally.

**Comment by jorgepiloto** [comment]
Thanks for the comment, @plule-ansys. I though it would be useful to have an issue remembering that not all tools configuration were moved to the `pyprojec.toml` file.

Anyway, I agree with your point. We can close this issue.
